In [58]:
import pandas as pd
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
# df

# df2 = df.groupby('학교').get_group('구로고')
# df3 = df.groupby('학교').get_group('디지털고')
# df3

# df.groupby('학교').size()
# df.groupby('학교').count()

# df.groupby('학교')['키'].mean()
# df.groupby('학교')['키'].mean().sort_values(ascending=False)
# df.groupby('학교')[['국어','영어']].mean()

In [44]:
df.groupby('학교').count()
# df['학교'].value_counts()

      이름  키  국어  영어  수학  과학  사회  SW특기  학년
학교
구로고    5  5   5   5   5   5   5     3   5
디지털고   3  3   3   3   3   3   3     3   3

In [59]:
df['학년'] = [3,3,2,1,1,3,2,2]
# df.groupby(['학교','학년']).size()
# df.groupby(['학교','학년']).count()
# df.groupby('학교')['학년'].value_counts().loc['구로고']
# df.groupby('학교')['학년'].value_counts().loc['디지털고']

In [66]:
df.groupby('학년')['키'].mean().sort_values(ascending=True)
df.groupby('학년')['국어'].mean().sort_values(ascending=True)
df.groupby('학년')[['국어','영어']].mean().sort_values('국어', ascending=False)

           국어         영어
학년
2   78.333333  75.000000
3   70.000000  73.333333
1   27.500000  40.000000

In [69]:
df.groupby('학교')[['국어', '영어', '수학']].mean().sort_values('국어', ascending=False)

             국어         영어         수학
학교
디지털고  78.333333  83.333333  76.666667
구로고   53.000000  55.000000  60.000000