In [248]:
import pandas as pd
import numpy as np
df = pd.read_csv('file1/chipotle.tsv', sep='\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [249]:
# df.sort_values('item_name', ascending=True)
# df.groupby('item_name').count()
# df['item_name'].value_counts().head(10)
# df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(10)

df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float)
df['item_price'].mean()     # 결과값  np.float64(7.464335785374297)
df.sort_values('item_price', ascending=False)

# df.groupby('order_id')['item_price'].sum().sort_values(ascending=False).head(10)
# df.groupby('order_id')['item_price'].mean().sort_values(ascending=False).head(10)

df2 = df.groupby('order_id')['item_price'].sum()
df2 = pd.DataFrame(df2)
# df2
df2['item_price'].sort_values(ascending=False).head(10)
filt1 = df2['item_price']>=100
df2[filt1]

          item_price
order_id
205           109.90
491           102.00
511           104.59
691           118.25
926           205.25
1443          160.74
1483          139.00
1786          114.30

In [ ]:
# filt2 = (df['item_name'] == 'Chicken Bowl') & (df['quantity'] >=2)
# df[filt2]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$17.50
282,124,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$17.50
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
415,181,2,Chicken Bowl,[Tomatillo Red Chili Salsa],$17.50
654,271,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$17.50
976,401,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$17.50
1017,418,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Black Beans]]",$17.50
1106,457,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$17.50
1429,578,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...",$22.50
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$26.25
1588,643,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$17.50
1832,741,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Sour Cream,...",$21.96
2075,837,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",$21.96
2106,848,2,Chicken Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$17.50
2339,932,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$16.98
2510,997,2,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$22.50
2525,1004,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$21.96
2580,1023,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$16.98
2771,1100,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$16.98
2942,1170,2,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",$21.96
3080,1227,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$16.98
3133,1249,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$16.98
3151,1257,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",$21.96
3423,1374,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",$17.50
3508,1410,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",$21.96
3612,1447,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",$16.98
3618,1449,2,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$16.98
3663,1465,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$16.98
3843,1540,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Pinto...",$21.96
3976,1593,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$16.98
4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$22.50
4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$17.50