In [3]:
import pandas as pd

In [9]:
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}
df = pd.DataFrame(data)
df.set_index('번호', inplace=True)
df

     이름       달러   우대
번호
1번  홍길동  $19,700   90
2번  유관순  $18,400   40
3번  이순신  $16,800   80
4번  강감찬  $18,700   40
5번   김구  $18,800   15
6번  김유신  $20,200   80
7번  홍길자  $18,800   55
8번  홍길순  $19,000  100

In [10]:

df['금액'] = 0
df['달러'] = df['달러'].str.replace('$','').str.replace(',','').astype(float)

def cal1(m):
    if m['우대'] >= 50:
        return m['달러']+(m['달러']+m['우대']*0.01)
    else:
        return m['달러']

df['금액'] = df.apply(cal1, axis=1)
df

     이름       달러   우대        금액
번호
1번  홍길동  19700.0   90  39400.90
2번  유관순  18400.0   40  18400.00
3번  이순신  16800.0   80  33600.80
4번  강감찬  18700.0   40  18700.00
5번   김구  18800.0   15  18800.00
6번  김유신  20200.0   80  40400.80
7번  홍길자  18800.0   55  37600.55
8번  홍길순  19000.0  100  38001.00