In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('file01/score.xlsx', index_col='지원번호')
df

       이름    학교   신장   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    송근열  디지털고  190  100   85   90  95  95          C#

### 기본통계 확인

In [4]:
# df.describe() : 숫자 통계 확인
# df.info() : 컬럼의 기본정보 확인

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   신장      8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 940.0+ bytes

In [9]:
df.describe() #std 표준편차 mean 평균

               신장          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [12]:
df.shape
# 8행 9열 (8, 9)

(8, 9)

In [19]:
# df.head() # 상위 5개 행 확인
# df.tail() # 하위 5개 행 확인
# df.head(3) # 상위 3개 행 확인
# df.tail(3) # 하위 3개 행 확인
# df.values  # 데이터의 numpy 배열 형태로 반환
# df.index # 행 인덱스 확인
# df.columns # 열 인덱스 확인

In [1]:
# df['신장'].max() # 신장 컬럼의 최대값 확인
# df['신장'].min() # 신장 컬럼의 최소값 확인
# df['신장'].mean() # 신장 컬럼의 평균값 확인
# df['신장'].std() # 신장 컬럼의 표준편차 확인
# df['신장'].count() # 신장 컬럼의 통계 확인

In [ ]:
# df['신장'].max() # 신장 컬럼의 최대값 확인
# df['신장'].min() # 신장 컬럼의 최소값 확인
# df['신장'].nlargest(3) # 신장 컬럼의 상위 3개 값 확인
# df['신장'].nsmallest(3) # 신장 컬럼의 하위 3개 값 확인
# df['학교'].unique() # 학교 컬럼의 고유값 확인