In [20]:
import pandas as pd
df = pd.read_excel('file01/score.xlsx', index_col='지원번호')

### loc 이름으로 검색 / iloc 인덱스로 검색

In [ ]:
# df.loc['1번']             # Row 한 개 출력
# df.loc[['1번', '3번']]    # Rovw 두 개 이상 출력
# df.loc['1번', '이름']     # 1번 Row의 이름을 출력
# df.loc['1번':'4번']         # 1번~4번 Row 출력
# df.loc['1번':'4번', '이름':'국어']        # Row 슬라이싱 가능
# df.loc['1번':'4번', ['이름','SW특기']]      
# df.loc[['1번','4번'], ['이름','SW특기']]      
# df[df.columns[1:5]]         # Column 슬라이싱 방법

In [30]:
# df.iloc[0]    #df.loc['1번']와 결과값 동일    
# df.iloc[0:4]
# df.iloc[0,4]    #결과값 np.int64(85)
# df.iloc[[0,1,4]]    
# df.iloc[0:3, 1:5]
# df.iloc[[0,2], 1:5]
# df.iloc[[0,2], [1,3,5]]

In [59]:
df = pd.read_excel('file01/census2507_12.xlsx', skiprows=3, index_col='행정기관', usecols='B:D, J:O')
# df
df.iloc[[0,2,3], [0,1,4,5]]

c:\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

              총 인구수     연령구간인구수     70~79세     80~89세
행정기관
전국       51,159,889  51,159,889  4,381,844  2,144,715
부산광역시     3,251,625   3,251,625    352,270    152,648
대구광역시     2,357,040   2,357,040    215,025    102,012

In [69]:
df = pd.read_excel('file01/합계출산율_20260929152936.xlsx', sheet_name='Sheet1')
df.set_index('Unnamed: 0', inplace=True)
df.index.rename('제목', inplace=True)
df[df.columns[[0,3,4,6]]]
# df.iloc[:, [0,3,4,6]]

           2016     2019     2020     2022
제목
출생아 수   406.200  302.700  272.300  249.200
합계 출산율    1.172    0.918    0.837    0.778

In [79]:
df = df.T

In [81]:
df
df.iloc[[0,3,4,6]]

제목    출생아 수  합계 출산율
2016  406.2   1.172
2019  302.7   0.918
2020  272.3   0.837
2022  249.2   0.778