In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

In [2]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('file0/namu1.csv')
df

,Unnamed: 0,title,url
0,0,틀:화성시의 시설+12,https://namu.wiki/w/%ED%8B%80:%ED%99%94%EC%84%...
1,1,사실은 에로했던 동화 빨간 망토0,https://namu.wiki/w/%EC%82%AC%EC%8B%A4%EC%9D%8...
2,2,네 가지 소원/7회전+25,https://namu.wiki/w/%EB%84%A4%20%EA%B0%80%EC%A...
3,3,레안드로 파레데스+31,https://namu.wiki/w/%EB%A0%88%EC%95%88%EB%93%9...
4,4,홍지원(이름 없는 여자)+3,https://namu.wiki/w/%ED%99%8D%EC%A7%80%EC%9B%9...
...,...,...,...
95,95,사용자:Seho07+20,https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%9...
96,96,동화약품-2,https://namu.wiki/w/%EB%8F%99%ED%99%94%EC%95%B...
97,97,삼요정 SAY YA!!!+71,https://namu.wiki/w/%EC%82%BC%EC%9A%94%EC%A0%9...
98,98,상벌점 괴물+1,https://namu.wiki/w/%EC%83%81%EB%B2%8C%EC%A0%9...
99,99,박병찬(2008)-2,https://namu.wiki/w/%EB%B0%95%EB%B3%91%EC%B0%A...

In [23]:
# for url in df['url']:
#     print(url)

In [ ]:
# # url_0 = "https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84"
# url_1 = "https://namu.wiki/w/%EB%A8%BC%EC%9E%91%EA%B7%80/%EB%93%B1%EC%9E%A5%EC%9D%B8%EB%AC%BC"
# res = requests.get(url_1)
# soup = BeautifulSoup(res.text, 'lxml')
# # # soup
# title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True)
# category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True)
# content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

# print(title, category)

먼작귀/등장인물 먼작귀/등장인물먼작귀일본 만화/등장인물애니메이션/등장인물

In [4]:
# SELENIUM으로 열기
df = pd.read_csv('file0/namu1.csv')
data = []
for url in df['url']:
    namu_url = url
    # options = Options()
    # options.add_experimental_option("excludeSwitches", ["enable-automation"])
    # options.add_experimental_option("useAutomationExtension", False)
    # options.add_argument("--disable-blink-features=AutomationControlled")
    # browser = webdriver.Chrome(options=options)
    # browser.maximize_window()
    # browser.get(namu_url)
    # time.sleep(2)

    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text, 'lxml')
    title0 = soup.find('a',{'class':'J23-5aq4'})
    title = title0.get_text(strip=True) if title0 else None
    category0 = soup.find('ul',{'class':'EVpyuXop'})
    category = category0.get_text(strip=True) if category0 else None
    content0 = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content0.get_text(strip=True)  if content0 else None
    data.append({
        'title' : title,
        'category' : category,
        'content' : content 
    })

n_df = pd.DataFrame(data)
n_df
# n_df.to_csv('file0/namu_data.cvs')

,title,category,content
0,틀:화성시의 시설,화성시의 시설둘러보기 틀/건축물/자치단체별,경기도화성시의 시설[ 펼치기 · 접기 ]도시철도병점역어천역광역급행철도동탄역일반철도화...
1,사실은 에로했던 동화 빨간 망토,2013년 Windows 게임동인 게임에로게일본 게임판타지 게임RPG 만들기 게임,1. 개요2. 스토리3. 시스템4. 등장인물4.1. 빨간 망토4.2. 미스트4.3....
2,네 가지 소원/7회전,네 가지 소원에피소드 가이드,상위 문서:네 가지 소원[ 참가자 ]권혜수길호종박지혜배준성배채운이승은이충명장우준전성...
3,레안드로 파레데스,"1994년 출생2011년 데뷔부에노스 아이레스 주 출신 인물AC 키에보베로나/은퇴,...",CA 보카 주니어스2026 시즌 스쿼드1마르체신·2디 로요·3블랑코·4피갈·5파레데...
4,홍지원(이름 없는 여자),이름 없는 여자/등장인물한국 드라마 캐릭터,"골프선수에 대한 내용은홍지원(골프선수)문서를, 보디빌더에 대한 내용은홍지원(보디빌더..."
...,...,...,...
95,사용자:Seho07,NaN,NaN
96,동화약품,동화약품대한민국의 제약회사중구(서울특별시)의 기업코스피상장법인1897년 설립한국의 ...,대한민국의 100년 기업[ 펼치기 · 접기 ]두산㈜두산 / 1896~신한은행㈜신한은...
97,삼요정 SAY YA!!!,삼라만상(동인 서클)동방 어레인지/2019년 노래동방 어레인지/요정대전쟁2019년 ...,三妖精SAY YA!!!Three Fairies SAY YA!!!삼요정 SAY YA!...
98,상벌점 괴물,44교시 생존수업/등장인물/괴물,이 문서에스포일러가 포함되어 있습니다.이 문서가 설명하는 작품이나 인물 등에 대한 ...
99,박병찬(2008),2008년 출생대전 하나 시티즌/현역대한민국의 남자 축구 선수수비형 미드필더,대전 하나 시티즌2026 시즌스쿼드1이창근· 2박규현· 3김민덕· 4조성권· 5임종...

In [5]:
n_df.to_csv('file0/namu_data.cvs')